alias edsw="code ~/.config/sway/config"

alias l='eza --icons --group-directories-first'
alias la='eza --icons --all --group-directories-first'
alias ll='eza --icons -l --time-style=long-iso --group-directories-first'
alias lg='eza --icons -l --all --git --time-style=long-iso --group-directories-first'
alias lll='eza --icons -l --sort=modified --time-style=long-iso --group-directories-first'
alias cat='bat'
alias ccat='/usr/bin/cat'
alias grep='rg'
alias chef='docker run -it -p 8080:80 ghcr.io/gchq/cyberchef:latest'

# Git aliases.
alias gs='git status'
alias gc='git commit -m'
alias gf='git fetch --all'
alias gp='git pull'
alias gpp='git push'
alias ga='git add'
alias gaa='git add --all'
alias gd='git diff'
alias gds='git diff --staged'
alias gb='git branch'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gl='git log --oneline --decorate --graph --all'
alias grs='git restore'
alias grst='git restore --staged'
