set -g history-limit 100000
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi

if-shell 'infocmp -x tmux-256color >/dev/null 2>&1' \
  'set -g default-terminal "tmux-256color"' \
  'set -g default-terminal "screen-256color"'

set -as terminal-features ',alacritty*:RGB'
set -as terminal-features ',alacritty*:clipboard'
set -as terminal-features ',xterm*:clipboard'

if-shell 'tmux -V | grep -Eq "tmux (2\\.[6-9]|[3-9]\\.)"' \
  'set -s set-clipboard external' \
  'set -s set-clipboard on'
