general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = rgb(000000)
}

input-field {
    monitor =
    size = 320, 56
    outline_thickness = 2
    inner_color = rgb(111111)
    outer_color = rgb(a3be8c)
    check_color = rgb(ffb86c)
    fail_color = rgb(ff5555)
    font_color = rgb(ffffff)
    fade_on_empty = false
    hide_input = false
    placeholder_text = Password
    position = 0, -30
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date '+%Y-%m-%d %H:%M'
    color = rgb(ffffff)
    font_size = 18
    position = 0, 36
    halign = center
    valign = center
}
